language: ruby
install:
  - gem install jekyll bundler
  - bundle install
script: bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: _site
  on:
    branch: master
