theme: jekyll-theme-hacker
title: Cyclic Immunofluorescence
description: A Simple Approach to Highly Multiplexed Cell and Tissue Imaging
sass:
    sass_dir: ./_scss
plugins:
    - jekyll-redirect-from
